apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.20.2
  name: workshop-demo
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: 10.100.128.201
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: workshop-demo-cp
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: CloudStackDatacenterConfig
    name: workshop-demo
  eksaVersion: v0.20.2
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: workshop-demo-etcd
  gitOpsRef:
    kind: FluxConfig
    name: workshop-demo
  kubernetesVersion: "1.28"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: workshop-demo
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: CloudStackMachineConfig
      name: workshop-demo
    machineHealthCheck:
      maxUnhealthy: 40%
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackDatacenterConfig
metadata:
  name: workshop-demo
  namespace: default
spec:
  availabilityZones:
  - account: admin
    credentialsRef: global
    domain: ROOT
    managementApiEndpoint: http://10.100.0.1:8080/client/api
    name: az-1
    zone:
      name: Zone1
      network:
        name: SharedNet1

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  name: workshop-demo
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: rhel8-kube-1.28-eksa
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCufrBnHZm9uURyiV6Hnxt8MpyxKZiY3aXkNw0WieTViTe5mY03auUUmmsRTgMeIj42UcY52/T3IZoHXpT63naU+ucU5eda30ByYqze97cLoie7ipXHesiiBFOwwZ8ryU8mpJO6r8ADBw4MkTJBBT+O8vEDHZsH4bs6U8VhIXcwpzccarGKocM/XyYxhealLxPkZMQIhDxWwo0xv76wDaPyIQDNnScST9Iq+U5eYCmsY3F6Oo9EhHy0tg0H0S85Par4dkLZ51sVFKDYMH0w+RH0R+vD/LfIab4rkyRrEjkJKDFI5Vc84aC35QbAJFcel0PK9o0xOVMo+JMWHVY0U9VvfyLy2TinGhW3jogW7jTVv/bRhhoVWHkYqmmaV1gl6fTB5ql8D/30wGrt4Qc17JhpbR4Nc3qf1a+EzuBxvH/aWgWFv6GXnaLsPtBHtpPzcPgvitPj0IWyDFPHs/pluQXY1UNDNcjflRTOf6h0OpqY9DscYh28n0cjgtrs8q7mOEc4KbM4f8CPd0KUF12DZRfjpbQfPjgjv3bJss/06QDLKsbgjFIKxWvvdTGPYWq7WxniSXlnkc08SUf77EzaIaYsgW3Rkf1kWe+J0ycmZv7m/QrGpVhZnTw2XrJCU6a622Ro5BTuFYmu1uI+dLOH7yEt7Pgg6k95XN8KBzlUcdvHoQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: workshop-demo-etcd
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: rhel8-kube-1.28-eksa
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCufrBnHZm9uURyiV6Hnxt8MpyxKZiY3aXkNw0WieTViTe5mY03auUUmmsRTgMeIj42UcY52/T3IZoHXpT63naU+ucU5eda30ByYqze97cLoie7ipXHesiiBFOwwZ8ryU8mpJO6r8ADBw4MkTJBBT+O8vEDHZsH4bs6U8VhIXcwpzccarGKocM/XyYxhealLxPkZMQIhDxWwo0xv76wDaPyIQDNnScST9Iq+U5eYCmsY3F6Oo9EhHy0tg0H0S85Par4dkLZ51sVFKDYMH0w+RH0R+vD/LfIab4rkyRrEjkJKDFI5Vc84aC35QbAJFcel0PK9o0xOVMo+JMWHVY0U9VvfyLy2TinGhW3jogW7jTVv/bRhhoVWHkYqmmaV1gl6fTB5ql8D/30wGrt4Qc17JhpbR4Nc3qf1a+EzuBxvH/aWgWFv6GXnaLsPtBHtpPzcPgvitPj0IWyDFPHs/pluQXY1UNDNcjflRTOf6h0OpqY9DscYh28n0cjgtrs8q7mOEc4KbM4f8CPd0KUF12DZRfjpbQfPjgjv3bJss/06QDLKsbgjFIKxWvvdTGPYWq7WxniSXlnkc08SUf77EzaIaYsgW3Rkf1kWe+J0ycmZv7m/QrGpVhZnTw2XrJCU6a622Ro5BTuFYmu1uI+dLOH7yEt7Pgg6k95XN8KBzlUcdvHoQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: CloudStackMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: workshop-demo-cp
  namespace: default
spec:
  computeOffering:
    name: Large Instance
  template:
    name: rhel8-kube-1.28-eksa
  users:
  - name: capc
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCufrBnHZm9uURyiV6Hnxt8MpyxKZiY3aXkNw0WieTViTe5mY03auUUmmsRTgMeIj42UcY52/T3IZoHXpT63naU+ucU5eda30ByYqze97cLoie7ipXHesiiBFOwwZ8ryU8mpJO6r8ADBw4MkTJBBT+O8vEDHZsH4bs6U8VhIXcwpzccarGKocM/XyYxhealLxPkZMQIhDxWwo0xv76wDaPyIQDNnScST9Iq+U5eYCmsY3F6Oo9EhHy0tg0H0S85Par4dkLZ51sVFKDYMH0w+RH0R+vD/LfIab4rkyRrEjkJKDFI5Vc84aC35QbAJFcel0PK9o0xOVMo+JMWHVY0U9VvfyLy2TinGhW3jogW7jTVv/bRhhoVWHkYqmmaV1gl6fTB5ql8D/30wGrt4Qc17JhpbR4Nc3qf1a+EzuBxvH/aWgWFv6GXnaLsPtBHtpPzcPgvitPj0IWyDFPHs/pluQXY1UNDNcjflRTOf6h0OpqY9DscYh28n0cjgtrs8q7mOEc4KbM4f8CPd0KUF12DZRfjpbQfPjgjv3bJss/06QDLKsbgjFIKxWvvdTGPYWq7WxniSXlnkc08SUf77EzaIaYsgW3Rkf1kWe+J0ycmZv7m/QrGpVhZnTw2XrJCU6a622Ro5BTuFYmu1uI+dLOH7yEt7Pgg6k95XN8KBzlUcdvHoQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: workshop-demo
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/workshop-demo
  github:
    owner: htquach
    personal: true
    repository: eks-anywhere
  systemNamespace: flux-system

---
