apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helm-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/eks-anywhere/fluxcd/helm-controller:v1.0.1-eks-a-74
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/eks-anywhere/fluxcd/kustomize-controller:v1.3.0-eks-a-74
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/eks-anywhere/fluxcd/notification-controller:v1.3.0-eks-a-74
            name: manager
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: source-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - image: public.ecr.aws/eks-anywhere/fluxcd/source-controller:v1.3.0-eks-a-74
            name: manager
